### PR TITLE
Make subnet scope broader and add more control options

### PR DESCRIPTION
**Pull request by 0xb1b1**
Change subnet scope to /16, add client management and docker build environment variables

### CODE REVIEW

**Review by denisix — COMMENTED** [review]
please change 0xb1b1 to denisix if you want to merge with existing repo, thanks

**Review by denisix — COMMENTED** [review]
what is the purpose of 'restart' script?

**Comment by denisix** [comment]
added your fixes [thanks!] + added subnet customization, please check, thanks!

**Comment by 0xb1b1** [comment]
> added your fixes [thanks!] + added subnet customization, please check, thanks!

I'll check that out :)

Also, I've changed 0xb1b1 -> denisix in README. Thanks for reminding! I use my tag to keep track of debug builds

P.S.: Oh, it looks like you've added most of the changes. As for the restart script, please do add it; it's responsible for server restarts on clientcontrol updates - without it, revoked users will be able to connect to the server
Reference:
```
revoke() {
    NAME=$1
    if [ -e "/etc/wireguard/clients/$NAME.pub" ]; then
        mv /etc/wireguard/clients/$NAME.pub /etc/wireguard/clients/$NAME-REV.pub
        restart
    else
	if [ "$CLIENTCONTROL_NO_LOGS" -eq 0 ]
	then
        	printf "$NAME has not been created yet"
        fi
	exit 1
    fi
}

unrevoke() {
    NAME=$1
    if [ -e "/etc/wireguard/clients/$NAME-REV.pub" ]; then
        mv /etc/wireguard/clients/$NAME-REV.pub /etc/wireguard/clients/$NAME.pub
        restart
    elif [ -e "/etc/wireguard/clients/$NAME.pub" ]; then
        if [ "$CLIENTCONTROL_NO_LOGS" -eq 0 ]
	then
		printf "$NAME has not been revoked yet"
	fi
	exit 1
    else
        if [ "$CLIENTCONTROL_NO_LOGS" -eq 0 ]
	then
		printf "$NAME has not been created yet"
        fi
	exit 1
    fi
}
```

**Comment by 0xb1b1** [comment]
I successfully changed everything in my repo; also, there's a small fix that changes 1 to "1" inside a script to ensure that `test` does not fail. How do we merge?

EDIT: Oh, seems like we can't! Not a problem though. If you decide to add the restart script (which I do recommend including in the build) it'll be easier for me to re-fork your repo

**Comment by denisix** [comment]
sorry, I will be at PC soon, will check everything, thank you!

**Comment by 0xb1b1** [comment]
> sorry, I will be at PC soon, will check everything, thank you!

Hi! You could copy everything that's needed to your repository (including `.drone,yml` if you use Drone CI/Woodpecker CI) and mention me like this (if you want): `Co-authored-by: 0xb1b1 <voxelflee@protonmail.com>`

Thanks and have a great day! :)

**Pull request merged**
